parser: !!python/object:argparse.Namespace
  accumulation_steps: 1
  base_model: Qwen/Qwen3-4B-Instruct-2507
  checkpoint_dir: ../../checkpoint/
  ckpt_path: null
  clip: 1.0
  data_dir: ../data/
  data_names: null
  dataset_name: GEM/web_nlg
  devices: 1
  do_test_only: false
  do_train_only: true
  dropout: 0.1
  epochs: 5
  eval_freq: 50
  eval_print_freq: 50
  fixed_lr: false
  gradient_accumulation_steps: 1
  load_from: null
  local_rank: -1
  lora_alpha: 32
  lora_dropout: 0.1
  lora_r: 8
  lr: 0.0001
  lr_scheduler_step: false
  main_port: -1
  max_seq_length: 256
  maxload: -1
  model_path: none
  n_shot: 0
  name: experiment_name
  num_workers: 0
  optim: adam
  per_gpu_batch_size: 64
  run_name: null
  save_freq: 5000
  scheduler: fixed
  scheduler_steps: null
  seed: 0
  total_steps: 1000
  use_lora: false
  wandb: false
  wandb_key: 330f5e7f972f801a6a619738f037a401d797469d
  warmup_ratio: 0.3
  weight_decay: 0.1
  write_crossattention_scores: false
  write_results: false
